export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const REFRESH_RESULTS = "REFRESH_RESULTS";
export const LOAD_MORE_RESULTS = "LOAD_MORE_RESULTS";
export const FETCH_SEARCH = "FETCH_SEARCH";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const CHANGE_VIEWABLE_ITEMS_INDEX = "CHANGE_VIEWABLE_ITEMS_INDEX";
